# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "AngÄ¼u"
languagedirection = "ltr"
title = "Kungs"
weight = 2
[lv]
languageName = "ðŸ‡±ðŸ‡»"
languagedirection = "2tr"
title = "Kungs"
weight = 1
[ru]
languageName = "Krievu"
languagedirection = "3tr"
title = "Kungs"
weight = 4
[uk]
languageName = "UkraiÅ†u"
languagedirection = "4tr"
title = "Kungs"
weight = 3


