# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "<img
  src="https://flagcdn.com/gb.svg"
  width="30"
  alt="United Kingdom">"
languagedirection = "ltr"
title = "Kungs"
weight = 2
[lv]
languageName = "<img src='https://flagcdn.com/20x15/lv.png'"
languagedirection = "2tr"
title = "Kungs"
weight = 1
[ru]
languageName = "Krievu"
languagedirection = "3tr"
title = "Kungs"
weight = 4
[uk]
languageName = "UkraiÅ†u"
languagedirection = "4tr"
title = "Kungs"
weight = 3


